spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aniljha91/microservices-Arch
          search-paths:
            - '/config-server/src/main/resources/shared/aws'
          username: aniljha91
          password: Github_9791
          


eureka:
  client:
    serviceUrl:
       defaultZone: http://ec2-34-212-49-187.us-west-2.compute.amazonaws.com:8762/eureka/
      
  instance:
    prefer-ip-address: true
    
server:
  port: 8889

security:
  user: 
    password: password
