logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

spring:
  rabbitmq:
    host: rabbitmq
  zipkin:
    baseUrl: http://ec2-34-212-49-187.us-west-2.compute.amazonaws.com:3333
    
    
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 20000
    ConnectTimeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-34-212-49-187.us-west-2.compute.amazonaws.com:8762/eureka/
      
  instance:
    prefer-ip-address: true
    
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://ec2-34-212-49-187.us-west-2.compute.amazonaws.com:5000/uaa/users/current

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  config:
    stream:
      maxConcurrentConnections: 20
      
      
#swagger
swagger:
  title: You have swagger!
  description: Swagger Page
  #version: {build.version}
  termsOfServiceUrl: 
  contact:
      name:
      url: 
      email:
  licenseUrl:      