#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/aniljha91/microservices-Arch/tree/master/config-server
#          searchPaths: ConfigData
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native

#server:
#  port: 8889

#security:
#  user: 
#    password: password



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aniljha91/microservices-Arch
          search-paths:
          - '/config-server/src/main/resources/shared'
          username: aniljha91
          password: Github_9791




server:
  port: 8889
  
security:
  user: 
    password: password